### ISSUE TITLE
Accessing tutorial

### ISSUE THREAD

**Issue by statsgirl1** [bhattacharya-a-bt/MOSTWAS#1]
Hi there,

I haven't been able to access the tutorial on (https://bhattacharya-a-bt.github.io/MOSTWAS/). I was wondering if the link has changed?

**Comment by statsgirl1** [comment]
I realized my ad blocker was the issue. Sorry.

**Comment by bhattacharya-a-bt** [comment]
No problem - let me know if you have any other questions.
